[build]
  command = "npm run build"
  publish = "."

[[headers]]
  for = "./js/*.js"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "./css/*.css"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "./*.html"
  [headers.values]
    Content-Encoding = "gzip"

[[headers]]
  for = "./pages/*.html"
  [headers.values]
    Content-Encoding = "gzip"
